### PR TITLE
Prevent FLAML logging warning on import

### PR DESCRIPTION
**Pull request by marklysze**
## Why are these changes needed?

Previous FLAML PR (#61) did not fully remove the FLAML warning showing when running AutoGen workflows due to FLAML in `completion.py`.

So, this PR will add a temporary logging NullHandler during import of FLAML functions in `completion.py`, then will remove the NullHandler afterwards.

## Related issue number

#61

## Checks

- [ ] I've included any doc changes needed for https://autogen-ai.github.io/autogen/. See https://autogen-ai.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by sonichi** [comment]
@thinkall FYI. This might be an issue to solve in FLAML.

**Review by qingyun-wu — APPROVED** [review]
LGTM. Thanks Mark!

**Comment by thinkall** [comment]
> @thinkall FYI. This might be an issue to solve in FLAML.

The warning message in FLAML is expected. I would suggest adding a logger instead of importing it from FLAML. This PR also works well though.

**Comment by marklysze** [comment]
> > @thinkall FYI. This might be an issue to solve in FLAML.
> 
> The warning message in FLAML is expected. I would suggest adding a logger instead of importing it from FLAML. This PR also works well though.

Hi @thinkall, I tried that in a previous PR. I don't believe we're importing one now from FLAML. I think it's logging a warning regarding automl automatically.

**Comment by thinkall** [comment]
> > > @thinkall FYI. This might be an issue to solve in FLAML.
> > 
> > 
> > The warning message in FLAML is expected. I would suggest adding a logger instead of importing it from FLAML. This PR also works well though.
> 
> Hi @thinkall, I tried that in a previous PR. I don't believe we're importing one now from FLAML. I think it's logging a warning regarding automl automatically.

I see. You're right.

**Pull request merged**
