### PR TITLE
Custom Model Client class support for 'auto' speaker selection in Group Chat

### PR DESCRIPTION
**Pull request by marklysze**
## Why are these changes needed?

If you are you using a custom model client class  and want to use it for the the inner speaker selection chat when using `auto` speaker selection, it isn't possible at the moment as it uses the GroupChatManager's config by default.

This addresses this bug by registering the custom model client class during the creation of the inner `speaker_selection_agent`.

To assign a custom model client class and config to the inner `auto` speaker selection agent you need to register the config and client class with the GroupChat object, see example below.

```
# Import your custom model client class
from mycustommodelclient import MyCustomModelClient

# Example llm_config
custom_llm_config = {
    "config_list":
    [
        {
            "model_client_cls": "MyCustomModelClient",
        }
    ]
}

# Updated GroupChat creation with config and client classes registered
gc = GroupChat(
    agents=[mark, alexandra, elizabeth],
    speaker_selection_method="auto",
    allow_repeat_speaker=False,
    select_speaker_auto_verbose=True,
    select_speaker_auto_llm_config=custom_llm_config,
    select_speaker_auto_model_client_cls=MyCustomModelClient,
    max_round=5,
    messages=[]
)
```

Two new properties exist:
- **select_speaker_auto_llm_config**: Set this to your llm_config
- **select_speaker_auto_model_client_cls**: Set this to the class of your custom model client

Documentation update to come.

## Related issue number

Raised by [Jason_DataScience on Discord](https://discord.com/channels/1153072414184452236/1295731167730864138/1295731167730864138).

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [X] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [X] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by Hk669** [comment]
@marklysze have you tested this PR.

**Comment by marklysze** [comment]
Hey @Hk669, yes, I've tested it and also passes pytest :)

I'm in the process of adding some documentation before final review.

**Comment by marklysze** [comment]
Okay, @Hk669, I've added a documentation page as well, so good for review.

**Comment by Hk669** [comment]
Thanks @marklysze , let me go through the docs and test it locally.

**Review by qingyun-wu — APPROVED** [review]
Looks good! Thanks Mark!

**Comment by qingyun-wu** [comment]
@Hk669 Have you finished testing? Thank you!

**Pull request merged**
