### PR TITLE
bump version to 0.3.1

### PR DESCRIPTION
**Pull request by sonichi**
## Why are these changes needed?

For new release.

## Checks

- [ ] I've included any doc changes needed for https://autogen-ai.github.io/autogen/. See https://autogen-ai.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by henrytwo — APPROVED** [review]

**Review by marklysze — APPROVED** [review]

**Review by BabyCNM — APPROVED** [review]
LGTM.

**Review by Hk669 — APPROVED** [review]
looks good to me.

**Comment by Hk669** [comment]
@sonichi i think we can include these PRs into this release.
#54 #56

**Comment by sonichi** [comment]
> @sonichi i think we can include these PRs into this release. #54 #56

#56 looks ready. #54 might take a little longer.

**Pull request merged**
